name = "ntfy-reverse-proxy"
main = "src/index.ts"
compatibility_date = "2024-01-17"

############
## Routes ##
############
routes = [
  { pattern = "abcde.ntfy.example.com", custom_domain = true },
  { pattern = "12345.ntfy.example.com", custom_domain = true },
]

#####################
## Vars: Countries ##
#####################
[vars.countries]
mode = "allow"
list = [
  "US",
  "CA",
]

########################
## Vars: IP addresses ##
########################
[vars.ip_addresses]
mode = "disallow"
list = [
  "127.0.0.1",
  "::1",
]

###################
## Vars: Servers ##
###################
[vars.servers]
mode = "send-once"
list = [
  { subdomain = "abcde", topic = "topic-1", server = "https://server-1-ntfy.sh", token = "tk_m61tag95tx" },
  { subdomain = "abcde", topic = "topic-1", server = "https://server-2-ntfy.sh", token = "tk_mdo4e750xv" },
  { subdomain = "12345", topic = "topic-2", server = "https://server-1-ntfy.sh", token = "tk_3m6p0o830s" },
  { subdomain = "12345", topic = "topic-2", server = "https://server-2-ntfy.sh", token = "tk_ecpoh2t79b" },
]

####################
## Vars: Settings ##
####################
[vars.settings]
force_https = true
show_response_output = true
show_visitor_info = true

#######################
## Vars: User agents ##
#######################
[vars.user_agents]
mode = "allow"
list = [
  "custom-user-agent",
]
