/**
 * Tests - Worker - Pipeline - Receive.
 *
 * @since 2.0.0
 */
export type Tests_Worker_Pipeline_Receive_Receive_BaseDomain = string;

export type Tests_Worker_Pipeline_Receive_Receive_DoesNotRedirectHTTPOnLocalhost_Request = Request;

export type Tests_Worker_Pipeline_Receive_Receive_DoesNotRedirectHTTPOnLocalhost_Result_Method = string;
export type Tests_Worker_Pipeline_Receive_Receive_DoesNotRedirectHTTPOnLocalhost_Result_Hostname = string;
export type Tests_Worker_Pipeline_Receive_Receive_DoesNotRedirectHTTPOnLocalhost_Result_Url = string;
export type Tests_Worker_Pipeline_Receive_Receive_DoesNotRedirectHTTPOnLocalhost_Result_Headers = Headers;
export type Tests_Worker_Pipeline_Receive_Receive_DoesNotRedirectHTTPOnLocalhost_Result_RawBody = ArrayBuffer;
export type Tests_Worker_Pipeline_Receive_Receive_DoesNotRedirectHTTPOnLocalhost_Result_IsGet = boolean;
export type Tests_Worker_Pipeline_Receive_Receive_DoesNotRedirectHTTPOnLocalhost_Result_Redirect = string;
export type Tests_Worker_Pipeline_Receive_Receive_DoesNotRedirectHTTPOnLocalhost_Result_Error = string;

export type Tests_Worker_Pipeline_Receive_Receive_DoesNotRedirectHTTPOnLocalhost_Result = {
  method: Tests_Worker_Pipeline_Receive_Receive_DoesNotRedirectHTTPOnLocalhost_Result_Method;
  hostname: Tests_Worker_Pipeline_Receive_Receive_DoesNotRedirectHTTPOnLocalhost_Result_Hostname;
  url: Tests_Worker_Pipeline_Receive_Receive_DoesNotRedirectHTTPOnLocalhost_Result_Url;
  headers: Tests_Worker_Pipeline_Receive_Receive_DoesNotRedirectHTTPOnLocalhost_Result_Headers;
  rawBody: Tests_Worker_Pipeline_Receive_Receive_DoesNotRedirectHTTPOnLocalhost_Result_RawBody;
  isGet: Tests_Worker_Pipeline_Receive_Receive_DoesNotRedirectHTTPOnLocalhost_Result_IsGet;
  redirect?: Tests_Worker_Pipeline_Receive_Receive_DoesNotRedirectHTTPOnLocalhost_Result_Redirect;
  error?: Tests_Worker_Pipeline_Receive_Receive_DoesNotRedirectHTTPOnLocalhost_Result_Error;
};

export type Tests_Worker_Pipeline_Receive_Receive_ExtractsHeadersFromTheRequest_Request = Request;

export type Tests_Worker_Pipeline_Receive_Receive_ExtractsHeadersFromTheRequest_Result_Method = string;
export type Tests_Worker_Pipeline_Receive_Receive_ExtractsHeadersFromTheRequest_Result_Hostname = string;
export type Tests_Worker_Pipeline_Receive_Receive_ExtractsHeadersFromTheRequest_Result_Url = string;
export type Tests_Worker_Pipeline_Receive_Receive_ExtractsHeadersFromTheRequest_Result_Headers = Headers;
export type Tests_Worker_Pipeline_Receive_Receive_ExtractsHeadersFromTheRequest_Result_RawBody = ArrayBuffer;
export type Tests_Worker_Pipeline_Receive_Receive_ExtractsHeadersFromTheRequest_Result_IsGet = boolean;
export type Tests_Worker_Pipeline_Receive_Receive_ExtractsHeadersFromTheRequest_Result_Redirect = string;
export type Tests_Worker_Pipeline_Receive_Receive_ExtractsHeadersFromTheRequest_Result_Error = string;

export type Tests_Worker_Pipeline_Receive_Receive_ExtractsHeadersFromTheRequest_Result = {
  method: Tests_Worker_Pipeline_Receive_Receive_ExtractsHeadersFromTheRequest_Result_Method;
  hostname: Tests_Worker_Pipeline_Receive_Receive_ExtractsHeadersFromTheRequest_Result_Hostname;
  url: Tests_Worker_Pipeline_Receive_Receive_ExtractsHeadersFromTheRequest_Result_Url;
  headers: Tests_Worker_Pipeline_Receive_Receive_ExtractsHeadersFromTheRequest_Result_Headers;
  rawBody: Tests_Worker_Pipeline_Receive_Receive_ExtractsHeadersFromTheRequest_Result_RawBody;
  isGet: Tests_Worker_Pipeline_Receive_Receive_ExtractsHeadersFromTheRequest_Result_IsGet;
  redirect?: Tests_Worker_Pipeline_Receive_Receive_ExtractsHeadersFromTheRequest_Result_Redirect;
  error?: Tests_Worker_Pipeline_Receive_Receive_ExtractsHeadersFromTheRequest_Result_Error;
};

export type Tests_Worker_Pipeline_Receive_Receive_ExtractsHeadersFromTheRequest_HeaderValue = string | null;

export type Tests_Worker_Pipeline_Receive_Receive_ExtractsMetadataFromAValidPOSTRequest_Request = Request;

export type Tests_Worker_Pipeline_Receive_Receive_ExtractsMetadataFromAValidPOSTRequest_Result_Method = string;
export type Tests_Worker_Pipeline_Receive_Receive_ExtractsMetadataFromAValidPOSTRequest_Result_Hostname = string;
export type Tests_Worker_Pipeline_Receive_Receive_ExtractsMetadataFromAValidPOSTRequest_Result_Url = string;
export type Tests_Worker_Pipeline_Receive_Receive_ExtractsMetadataFromAValidPOSTRequest_Result_Headers = Headers;
export type Tests_Worker_Pipeline_Receive_Receive_ExtractsMetadataFromAValidPOSTRequest_Result_RawBody = ArrayBuffer;
export type Tests_Worker_Pipeline_Receive_Receive_ExtractsMetadataFromAValidPOSTRequest_Result_IsGet = boolean;
export type Tests_Worker_Pipeline_Receive_Receive_ExtractsMetadataFromAValidPOSTRequest_Result_Redirect = string;
export type Tests_Worker_Pipeline_Receive_Receive_ExtractsMetadataFromAValidPOSTRequest_Result_Error = string;

export type Tests_Worker_Pipeline_Receive_Receive_ExtractsMetadataFromAValidPOSTRequest_Result = {
  method: Tests_Worker_Pipeline_Receive_Receive_ExtractsMetadataFromAValidPOSTRequest_Result_Method;
  hostname: Tests_Worker_Pipeline_Receive_Receive_ExtractsMetadataFromAValidPOSTRequest_Result_Hostname;
  url: Tests_Worker_Pipeline_Receive_Receive_ExtractsMetadataFromAValidPOSTRequest_Result_Url;
  headers: Tests_Worker_Pipeline_Receive_Receive_ExtractsMetadataFromAValidPOSTRequest_Result_Headers;
  rawBody: Tests_Worker_Pipeline_Receive_Receive_ExtractsMetadataFromAValidPOSTRequest_Result_RawBody;
  isGet: Tests_Worker_Pipeline_Receive_Receive_ExtractsMetadataFromAValidPOSTRequest_Result_IsGet;
  redirect?: Tests_Worker_Pipeline_Receive_Receive_ExtractsMetadataFromAValidPOSTRequest_Result_Redirect;
  error?: Tests_Worker_Pipeline_Receive_Receive_ExtractsMetadataFromAValidPOSTRequest_Result_Error;
};

export type Tests_Worker_Pipeline_Receive_Receive_ExtractsRawBodyAsArrayBuffer_Body = string;

export type Tests_Worker_Pipeline_Receive_Receive_ExtractsRawBodyAsArrayBuffer_Request = Request;

export type Tests_Worker_Pipeline_Receive_Receive_ExtractsRawBodyAsArrayBuffer_Result_Method = string;
export type Tests_Worker_Pipeline_Receive_Receive_ExtractsRawBodyAsArrayBuffer_Result_Hostname = string;
export type Tests_Worker_Pipeline_Receive_Receive_ExtractsRawBodyAsArrayBuffer_Result_Url = string;
export type Tests_Worker_Pipeline_Receive_Receive_ExtractsRawBodyAsArrayBuffer_Result_Headers = Headers;
export type Tests_Worker_Pipeline_Receive_Receive_ExtractsRawBodyAsArrayBuffer_Result_RawBody = ArrayBuffer;
export type Tests_Worker_Pipeline_Receive_Receive_ExtractsRawBodyAsArrayBuffer_Result_IsGet = boolean;
export type Tests_Worker_Pipeline_Receive_Receive_ExtractsRawBodyAsArrayBuffer_Result_Redirect = string;
export type Tests_Worker_Pipeline_Receive_Receive_ExtractsRawBodyAsArrayBuffer_Result_Error = string;

export type Tests_Worker_Pipeline_Receive_Receive_ExtractsRawBodyAsArrayBuffer_Result = {
  method: Tests_Worker_Pipeline_Receive_Receive_ExtractsRawBodyAsArrayBuffer_Result_Method;
  hostname: Tests_Worker_Pipeline_Receive_Receive_ExtractsRawBodyAsArrayBuffer_Result_Hostname;
  url: Tests_Worker_Pipeline_Receive_Receive_ExtractsRawBodyAsArrayBuffer_Result_Url;
  headers: Tests_Worker_Pipeline_Receive_Receive_ExtractsRawBodyAsArrayBuffer_Result_Headers;
  rawBody: Tests_Worker_Pipeline_Receive_Receive_ExtractsRawBodyAsArrayBuffer_Result_RawBody;
  isGet: Tests_Worker_Pipeline_Receive_Receive_ExtractsRawBodyAsArrayBuffer_Result_IsGet;
  redirect?: Tests_Worker_Pipeline_Receive_Receive_ExtractsRawBodyAsArrayBuffer_Result_Redirect;
  error?: Tests_Worker_Pipeline_Receive_Receive_ExtractsRawBodyAsArrayBuffer_Result_Error;
};

export type Tests_Worker_Pipeline_Receive_Receive_IdentifiesGETRequests_Request = Request;

export type Tests_Worker_Pipeline_Receive_Receive_IdentifiesGETRequests_Result_Method = string;
export type Tests_Worker_Pipeline_Receive_Receive_IdentifiesGETRequests_Result_Hostname = string;
export type Tests_Worker_Pipeline_Receive_Receive_IdentifiesGETRequests_Result_Url = string;
export type Tests_Worker_Pipeline_Receive_Receive_IdentifiesGETRequests_Result_Headers = Headers;
export type Tests_Worker_Pipeline_Receive_Receive_IdentifiesGETRequests_Result_RawBody = ArrayBuffer;
export type Tests_Worker_Pipeline_Receive_Receive_IdentifiesGETRequests_Result_IsGet = boolean;
export type Tests_Worker_Pipeline_Receive_Receive_IdentifiesGETRequests_Result_Redirect = string;
export type Tests_Worker_Pipeline_Receive_Receive_IdentifiesGETRequests_Result_Error = string;

export type Tests_Worker_Pipeline_Receive_Receive_IdentifiesGETRequests_Result = {
  method: Tests_Worker_Pipeline_Receive_Receive_IdentifiesGETRequests_Result_Method;
  hostname: Tests_Worker_Pipeline_Receive_Receive_IdentifiesGETRequests_Result_Hostname;
  url: Tests_Worker_Pipeline_Receive_Receive_IdentifiesGETRequests_Result_Url;
  headers: Tests_Worker_Pipeline_Receive_Receive_IdentifiesGETRequests_Result_Headers;
  rawBody: Tests_Worker_Pipeline_Receive_Receive_IdentifiesGETRequests_Result_RawBody;
  isGet: Tests_Worker_Pipeline_Receive_Receive_IdentifiesGETRequests_Result_IsGet;
  redirect?: Tests_Worker_Pipeline_Receive_Receive_IdentifiesGETRequests_Result_Redirect;
  error?: Tests_Worker_Pipeline_Receive_Receive_IdentifiesGETRequests_Result_Error;
};

export type Tests_Worker_Pipeline_Receive_Receive_RejectsUnsupportedHTTPMethods_Request = Request;

export type Tests_Worker_Pipeline_Receive_Receive_RejectsUnsupportedHTTPMethods_Result_Method = string;
export type Tests_Worker_Pipeline_Receive_Receive_RejectsUnsupportedHTTPMethods_Result_Hostname = string;
export type Tests_Worker_Pipeline_Receive_Receive_RejectsUnsupportedHTTPMethods_Result_Url = string;
export type Tests_Worker_Pipeline_Receive_Receive_RejectsUnsupportedHTTPMethods_Result_Headers = Headers;
export type Tests_Worker_Pipeline_Receive_Receive_RejectsUnsupportedHTTPMethods_Result_RawBody = ArrayBuffer;
export type Tests_Worker_Pipeline_Receive_Receive_RejectsUnsupportedHTTPMethods_Result_IsGet = boolean;
export type Tests_Worker_Pipeline_Receive_Receive_RejectsUnsupportedHTTPMethods_Result_Redirect = string;
export type Tests_Worker_Pipeline_Receive_Receive_RejectsUnsupportedHTTPMethods_Result_Error = string;

export type Tests_Worker_Pipeline_Receive_Receive_RejectsUnsupportedHTTPMethods_Result = {
  method: Tests_Worker_Pipeline_Receive_Receive_RejectsUnsupportedHTTPMethods_Result_Method;
  hostname: Tests_Worker_Pipeline_Receive_Receive_RejectsUnsupportedHTTPMethods_Result_Hostname;
  url: Tests_Worker_Pipeline_Receive_Receive_RejectsUnsupportedHTTPMethods_Result_Url;
  headers: Tests_Worker_Pipeline_Receive_Receive_RejectsUnsupportedHTTPMethods_Result_Headers;
  rawBody: Tests_Worker_Pipeline_Receive_Receive_RejectsUnsupportedHTTPMethods_Result_RawBody;
  isGet: Tests_Worker_Pipeline_Receive_Receive_RejectsUnsupportedHTTPMethods_Result_IsGet;
  redirect?: Tests_Worker_Pipeline_Receive_Receive_RejectsUnsupportedHTTPMethods_Result_Redirect;
  error?: Tests_Worker_Pipeline_Receive_Receive_RejectsUnsupportedHTTPMethods_Result_Error;
};

export type Tests_Worker_Pipeline_Receive_Receive_ReturnsRedirectForHTTPInProduction_Request = Request;

export type Tests_Worker_Pipeline_Receive_Receive_ReturnsRedirectForHTTPInProduction_Result_Method = string;
export type Tests_Worker_Pipeline_Receive_Receive_ReturnsRedirectForHTTPInProduction_Result_Hostname = string;
export type Tests_Worker_Pipeline_Receive_Receive_ReturnsRedirectForHTTPInProduction_Result_Url = string;
export type Tests_Worker_Pipeline_Receive_Receive_ReturnsRedirectForHTTPInProduction_Result_Headers = Headers;
export type Tests_Worker_Pipeline_Receive_Receive_ReturnsRedirectForHTTPInProduction_Result_RawBody = ArrayBuffer;
export type Tests_Worker_Pipeline_Receive_Receive_ReturnsRedirectForHTTPInProduction_Result_IsGet = boolean;
export type Tests_Worker_Pipeline_Receive_Receive_ReturnsRedirectForHTTPInProduction_Result_Redirect = string;
export type Tests_Worker_Pipeline_Receive_Receive_ReturnsRedirectForHTTPInProduction_Result_Error = string;

export type Tests_Worker_Pipeline_Receive_Receive_ReturnsRedirectForHTTPInProduction_Result = {
  method: Tests_Worker_Pipeline_Receive_Receive_ReturnsRedirectForHTTPInProduction_Result_Method;
  hostname: Tests_Worker_Pipeline_Receive_Receive_ReturnsRedirectForHTTPInProduction_Result_Hostname;
  url: Tests_Worker_Pipeline_Receive_Receive_ReturnsRedirectForHTTPInProduction_Result_Url;
  headers: Tests_Worker_Pipeline_Receive_Receive_ReturnsRedirectForHTTPInProduction_Result_Headers;
  rawBody: Tests_Worker_Pipeline_Receive_Receive_ReturnsRedirectForHTTPInProduction_Result_RawBody;
  isGet: Tests_Worker_Pipeline_Receive_Receive_ReturnsRedirectForHTTPInProduction_Result_IsGet;
  redirect?: Tests_Worker_Pipeline_Receive_Receive_ReturnsRedirectForHTTPInProduction_Result_Redirect;
  error?: Tests_Worker_Pipeline_Receive_Receive_ReturnsRedirectForHTTPInProduction_Result_Error;
};
