/**
 * Tests - Worker - Pipeline - Respond.
 *
 * @since 2.0.0
 */
export type Tests_Worker_Pipeline_Respond_Respond_ExcludesDebugInfoWhenShowResponseOutputIsFalse_SendResult_ResultsItem_Name = string;
export type Tests_Worker_Pipeline_Respond_Respond_ExcludesDebugInfoWhenShowResponseOutputIsFalse_SendResult_ResultsItem_Success = boolean;
export type Tests_Worker_Pipeline_Respond_Respond_ExcludesDebugInfoWhenShowResponseOutputIsFalse_SendResult_ResultsItem_Status = number;
export type Tests_Worker_Pipeline_Respond_Respond_ExcludesDebugInfoWhenShowResponseOutputIsFalse_SendResult_ResultsItem_Stages = string[];

export type Tests_Worker_Pipeline_Respond_Respond_ExcludesDebugInfoWhenShowResponseOutputIsFalse_SendResult_ResultsItem = {
  name: Tests_Worker_Pipeline_Respond_Respond_ExcludesDebugInfoWhenShowResponseOutputIsFalse_SendResult_ResultsItem_Name;
  success: Tests_Worker_Pipeline_Respond_Respond_ExcludesDebugInfoWhenShowResponseOutputIsFalse_SendResult_ResultsItem_Success;
  status: Tests_Worker_Pipeline_Respond_Respond_ExcludesDebugInfoWhenShowResponseOutputIsFalse_SendResult_ResultsItem_Status;
  stages: Tests_Worker_Pipeline_Respond_Respond_ExcludesDebugInfoWhenShowResponseOutputIsFalse_SendResult_ResultsItem_Stages;
};

export type Tests_Worker_Pipeline_Respond_Respond_ExcludesDebugInfoWhenShowResponseOutputIsFalse_SendResult_Results = Tests_Worker_Pipeline_Respond_Respond_ExcludesDebugInfoWhenShowResponseOutputIsFalse_SendResult_ResultsItem[];
export type Tests_Worker_Pipeline_Respond_Respond_ExcludesDebugInfoWhenShowResponseOutputIsFalse_SendResult_FallbackUsed = boolean;

export type Tests_Worker_Pipeline_Respond_Respond_ExcludesDebugInfoWhenShowResponseOutputIsFalse_SendResult = {
  results: Tests_Worker_Pipeline_Respond_Respond_ExcludesDebugInfoWhenShowResponseOutputIsFalse_SendResult_Results;
  fallbackUsed: Tests_Worker_Pipeline_Respond_Respond_ExcludesDebugInfoWhenShowResponseOutputIsFalse_SendResult_FallbackUsed;
};

export type Tests_Worker_Pipeline_Respond_Respond_ExcludesDebugInfoWhenShowResponseOutputIsFalse_Response = Response;

export type Tests_Worker_Pipeline_Respond_Respond_ExcludesDebugInfoWhenShowResponseOutputIsFalse_Body = Record<string, unknown>;

export type Tests_Worker_Pipeline_Respond_Respond_IncludesDebugInfoWhenShowResponseOutputIsTrue_SendResult_ResultsItem_Name = string;
export type Tests_Worker_Pipeline_Respond_Respond_IncludesDebugInfoWhenShowResponseOutputIsTrue_SendResult_ResultsItem_Success = boolean;
export type Tests_Worker_Pipeline_Respond_Respond_IncludesDebugInfoWhenShowResponseOutputIsTrue_SendResult_ResultsItem_Status = number;
export type Tests_Worker_Pipeline_Respond_Respond_IncludesDebugInfoWhenShowResponseOutputIsTrue_SendResult_ResultsItem_Stages = string[];

export type Tests_Worker_Pipeline_Respond_Respond_IncludesDebugInfoWhenShowResponseOutputIsTrue_SendResult_ResultsItem = {
  name: Tests_Worker_Pipeline_Respond_Respond_IncludesDebugInfoWhenShowResponseOutputIsTrue_SendResult_ResultsItem_Name;
  success: Tests_Worker_Pipeline_Respond_Respond_IncludesDebugInfoWhenShowResponseOutputIsTrue_SendResult_ResultsItem_Success;
  status: Tests_Worker_Pipeline_Respond_Respond_IncludesDebugInfoWhenShowResponseOutputIsTrue_SendResult_ResultsItem_Status;
  stages: Tests_Worker_Pipeline_Respond_Respond_IncludesDebugInfoWhenShowResponseOutputIsTrue_SendResult_ResultsItem_Stages;
};

export type Tests_Worker_Pipeline_Respond_Respond_IncludesDebugInfoWhenShowResponseOutputIsTrue_SendResult_Results = Tests_Worker_Pipeline_Respond_Respond_IncludesDebugInfoWhenShowResponseOutputIsTrue_SendResult_ResultsItem[];
export type Tests_Worker_Pipeline_Respond_Respond_IncludesDebugInfoWhenShowResponseOutputIsTrue_SendResult_FallbackUsed = boolean;

export type Tests_Worker_Pipeline_Respond_Respond_IncludesDebugInfoWhenShowResponseOutputIsTrue_SendResult = {
  results: Tests_Worker_Pipeline_Respond_Respond_IncludesDebugInfoWhenShowResponseOutputIsTrue_SendResult_Results;
  fallbackUsed: Tests_Worker_Pipeline_Respond_Respond_IncludesDebugInfoWhenShowResponseOutputIsTrue_SendResult_FallbackUsed;
};

export type Tests_Worker_Pipeline_Respond_Respond_IncludesDebugInfoWhenShowResponseOutputIsTrue_Response = Response;

export type Tests_Worker_Pipeline_Respond_Respond_IncludesDebugInfoWhenShowResponseOutputIsTrue_Body = Record<string, unknown>;

export type Tests_Worker_Pipeline_Respond_Respond_ReturnsFailedWhenAllServersFail_SendResult_ResultsItem_Name = string;
export type Tests_Worker_Pipeline_Respond_Respond_ReturnsFailedWhenAllServersFail_SendResult_ResultsItem_Success = boolean;
export type Tests_Worker_Pipeline_Respond_Respond_ReturnsFailedWhenAllServersFail_SendResult_ResultsItem_Status = number;
export type Tests_Worker_Pipeline_Respond_Respond_ReturnsFailedWhenAllServersFail_SendResult_ResultsItem_Stages = string[];

export type Tests_Worker_Pipeline_Respond_Respond_ReturnsFailedWhenAllServersFail_SendResult_ResultsItem = {
  name: Tests_Worker_Pipeline_Respond_Respond_ReturnsFailedWhenAllServersFail_SendResult_ResultsItem_Name;
  success: Tests_Worker_Pipeline_Respond_Respond_ReturnsFailedWhenAllServersFail_SendResult_ResultsItem_Success;
  status: Tests_Worker_Pipeline_Respond_Respond_ReturnsFailedWhenAllServersFail_SendResult_ResultsItem_Status;
  stages: Tests_Worker_Pipeline_Respond_Respond_ReturnsFailedWhenAllServersFail_SendResult_ResultsItem_Stages;
};

export type Tests_Worker_Pipeline_Respond_Respond_ReturnsFailedWhenAllServersFail_SendResult_Results = Tests_Worker_Pipeline_Respond_Respond_ReturnsFailedWhenAllServersFail_SendResult_ResultsItem[];
export type Tests_Worker_Pipeline_Respond_Respond_ReturnsFailedWhenAllServersFail_SendResult_FallbackUsed = boolean;

export type Tests_Worker_Pipeline_Respond_Respond_ReturnsFailedWhenAllServersFail_SendResult = {
  results: Tests_Worker_Pipeline_Respond_Respond_ReturnsFailedWhenAllServersFail_SendResult_Results;
  fallbackUsed: Tests_Worker_Pipeline_Respond_Respond_ReturnsFailedWhenAllServersFail_SendResult_FallbackUsed;
};

export type Tests_Worker_Pipeline_Respond_Respond_ReturnsFailedWhenAllServersFail_Response = Response;

export type Tests_Worker_Pipeline_Respond_Respond_ReturnsFailedWhenAllServersFail_Body = Record<string, unknown>;

/**
 * Tests - Worker - Pipeline - Respond - Respond - Returns Failed When Results Array Is Empty.
 *
 * @since 2.1.0
 */
export type Tests_Worker_Pipeline_Respond_Respond_ReturnsFailedWhenResultsArrayIsEmpty_SendResult_Results = never[];
export type Tests_Worker_Pipeline_Respond_Respond_ReturnsFailedWhenResultsArrayIsEmpty_SendResult_FallbackUsed = boolean;

export type Tests_Worker_Pipeline_Respond_Respond_ReturnsFailedWhenResultsArrayIsEmpty_SendResult = {
  results: Tests_Worker_Pipeline_Respond_Respond_ReturnsFailedWhenResultsArrayIsEmpty_SendResult_Results;
  fallbackUsed: Tests_Worker_Pipeline_Respond_Respond_ReturnsFailedWhenResultsArrayIsEmpty_SendResult_FallbackUsed;
};

export type Tests_Worker_Pipeline_Respond_Respond_ReturnsFailedWhenResultsArrayIsEmpty_Response = Response;

export type Tests_Worker_Pipeline_Respond_Respond_ReturnsFailedWhenResultsArrayIsEmpty_Body = Record<string, unknown>;

export type Tests_Worker_Pipeline_Respond_Respond_ReturnsPartialWhenSomeServersFail_SendResult_ResultsItem_Name = string;
export type Tests_Worker_Pipeline_Respond_Respond_ReturnsPartialWhenSomeServersFail_SendResult_ResultsItem_Success = boolean;
export type Tests_Worker_Pipeline_Respond_Respond_ReturnsPartialWhenSomeServersFail_SendResult_ResultsItem_Status = number;
export type Tests_Worker_Pipeline_Respond_Respond_ReturnsPartialWhenSomeServersFail_SendResult_ResultsItem_Stages = string[];

export type Tests_Worker_Pipeline_Respond_Respond_ReturnsPartialWhenSomeServersFail_SendResult_ResultsItem = {
  name: Tests_Worker_Pipeline_Respond_Respond_ReturnsPartialWhenSomeServersFail_SendResult_ResultsItem_Name;
  success: Tests_Worker_Pipeline_Respond_Respond_ReturnsPartialWhenSomeServersFail_SendResult_ResultsItem_Success;
  status: Tests_Worker_Pipeline_Respond_Respond_ReturnsPartialWhenSomeServersFail_SendResult_ResultsItem_Status;
  stages: Tests_Worker_Pipeline_Respond_Respond_ReturnsPartialWhenSomeServersFail_SendResult_ResultsItem_Stages;
};

export type Tests_Worker_Pipeline_Respond_Respond_ReturnsPartialWhenSomeServersFail_SendResult_Results = Tests_Worker_Pipeline_Respond_Respond_ReturnsPartialWhenSomeServersFail_SendResult_ResultsItem[];
export type Tests_Worker_Pipeline_Respond_Respond_ReturnsPartialWhenSomeServersFail_SendResult_FallbackUsed = boolean;

export type Tests_Worker_Pipeline_Respond_Respond_ReturnsPartialWhenSomeServersFail_SendResult = {
  results: Tests_Worker_Pipeline_Respond_Respond_ReturnsPartialWhenSomeServersFail_SendResult_Results;
  fallbackUsed: Tests_Worker_Pipeline_Respond_Respond_ReturnsPartialWhenSomeServersFail_SendResult_FallbackUsed;
};

export type Tests_Worker_Pipeline_Respond_Respond_ReturnsPartialWhenSomeServersFail_Response = Response;

export type Tests_Worker_Pipeline_Respond_Respond_ReturnsPartialWhenSomeServersFail_Body = Record<string, unknown>;

export type Tests_Worker_Pipeline_Respond_Respond_ReturnsSuccessWhenAllServersSucceed_SendResult_ResultsItem_Name = string;
export type Tests_Worker_Pipeline_Respond_Respond_ReturnsSuccessWhenAllServersSucceed_SendResult_ResultsItem_Success = boolean;
export type Tests_Worker_Pipeline_Respond_Respond_ReturnsSuccessWhenAllServersSucceed_SendResult_ResultsItem_Status = number;
export type Tests_Worker_Pipeline_Respond_Respond_ReturnsSuccessWhenAllServersSucceed_SendResult_ResultsItem_Stages = string[];

export type Tests_Worker_Pipeline_Respond_Respond_ReturnsSuccessWhenAllServersSucceed_SendResult_ResultsItem = {
  name: Tests_Worker_Pipeline_Respond_Respond_ReturnsSuccessWhenAllServersSucceed_SendResult_ResultsItem_Name;
  success: Tests_Worker_Pipeline_Respond_Respond_ReturnsSuccessWhenAllServersSucceed_SendResult_ResultsItem_Success;
  status: Tests_Worker_Pipeline_Respond_Respond_ReturnsSuccessWhenAllServersSucceed_SendResult_ResultsItem_Status;
  stages: Tests_Worker_Pipeline_Respond_Respond_ReturnsSuccessWhenAllServersSucceed_SendResult_ResultsItem_Stages;
};

export type Tests_Worker_Pipeline_Respond_Respond_ReturnsSuccessWhenAllServersSucceed_SendResult_Results = Tests_Worker_Pipeline_Respond_Respond_ReturnsSuccessWhenAllServersSucceed_SendResult_ResultsItem[];
export type Tests_Worker_Pipeline_Respond_Respond_ReturnsSuccessWhenAllServersSucceed_SendResult_FallbackUsed = boolean;

export type Tests_Worker_Pipeline_Respond_Respond_ReturnsSuccessWhenAllServersSucceed_SendResult = {
  results: Tests_Worker_Pipeline_Respond_Respond_ReturnsSuccessWhenAllServersSucceed_SendResult_Results;
  fallbackUsed: Tests_Worker_Pipeline_Respond_Respond_ReturnsSuccessWhenAllServersSucceed_SendResult_FallbackUsed;
};

export type Tests_Worker_Pipeline_Respond_Respond_ReturnsSuccessWhenAllServersSucceed_Response = Response;
