/**
 * Tests - Worker - Pipeline - Route.
 *
 * @since 2.0.0
 */
export type Tests_Worker_Pipeline_Route_MockSettings_WorkerName = string;
export type Tests_Worker_Pipeline_Route_MockSettings_BaseDomain = string;
export type Tests_Worker_Pipeline_Route_MockSettings_ShowResponseOutput = boolean;

export type Tests_Worker_Pipeline_Route_MockSettings = {
  worker_name: Tests_Worker_Pipeline_Route_MockSettings_WorkerName;
  base_domain: Tests_Worker_Pipeline_Route_MockSettings_BaseDomain;
  show_response_output: Tests_Worker_Pipeline_Route_MockSettings_ShowResponseOutput;
};

export type Tests_Worker_Pipeline_Route_MockServer_Name = string;
export type Tests_Worker_Pipeline_Route_MockServer_Server = string;
export type Tests_Worker_Pipeline_Route_MockServer_Token = string;

export type Tests_Worker_Pipeline_Route_MockServer = {
  name: Tests_Worker_Pipeline_Route_MockServer_Name;
  server: Tests_Worker_Pipeline_Route_MockServer_Server;
  token: Tests_Worker_Pipeline_Route_MockServer_Token;
};

export type Tests_Worker_Pipeline_Route_MockHttpContext_Id = string;
export type Tests_Worker_Pipeline_Route_MockHttpContext_Name = string;
export type Tests_Worker_Pipeline_Route_MockHttpContext_Type = 'http';
export type Tests_Worker_Pipeline_Route_MockHttpContext_Interpreter = 'plain-text';
export type Tests_Worker_Pipeline_Route_MockHttpContext_Topic = string;
export type Tests_Worker_Pipeline_Route_MockHttpContext_ErrorTopic = string | undefined;
export type Tests_Worker_Pipeline_Route_MockHttpContext_Mode = 'send-once';
export type Tests_Worker_Pipeline_Route_MockHttpContext_ShowVisitorInfo = boolean;
export type Tests_Worker_Pipeline_Route_MockHttpContext_PrimaryServer = string;
export type Tests_Worker_Pipeline_Route_MockHttpContext_Servers = string[];
export type Tests_Worker_Pipeline_Route_MockHttpContext_Token = string | undefined;

export type Tests_Worker_Pipeline_Route_MockHttpContext = {
  id: Tests_Worker_Pipeline_Route_MockHttpContext_Id;
  name: Tests_Worker_Pipeline_Route_MockHttpContext_Name;
  type: Tests_Worker_Pipeline_Route_MockHttpContext_Type;
  interpreter: Tests_Worker_Pipeline_Route_MockHttpContext_Interpreter;
  topic: Tests_Worker_Pipeline_Route_MockHttpContext_Topic;
  error_topic?: Tests_Worker_Pipeline_Route_MockHttpContext_ErrorTopic;
  mode: Tests_Worker_Pipeline_Route_MockHttpContext_Mode;
  show_visitor_info: Tests_Worker_Pipeline_Route_MockHttpContext_ShowVisitorInfo;
  primary_server: Tests_Worker_Pipeline_Route_MockHttpContext_PrimaryServer;
  servers: Tests_Worker_Pipeline_Route_MockHttpContext_Servers;
  token?: Tests_Worker_Pipeline_Route_MockHttpContext_Token;
};

export type Tests_Worker_Pipeline_Route_MockEmailContext_Id = string;
export type Tests_Worker_Pipeline_Route_MockEmailContext_Name = string;
export type Tests_Worker_Pipeline_Route_MockEmailContext_Type = 'email';
export type Tests_Worker_Pipeline_Route_MockEmailContext_Interpreter = 'pfsense';
export type Tests_Worker_Pipeline_Route_MockEmailContext_Topic = string;
export type Tests_Worker_Pipeline_Route_MockEmailContext_ErrorTopic = string | undefined;
export type Tests_Worker_Pipeline_Route_MockEmailContext_Mode = 'send-once';
export type Tests_Worker_Pipeline_Route_MockEmailContext_ShowVisitorInfo = boolean;
export type Tests_Worker_Pipeline_Route_MockEmailContext_PrimaryServer = string;
export type Tests_Worker_Pipeline_Route_MockEmailContext_Servers = string[];
export type Tests_Worker_Pipeline_Route_MockEmailContext_AllowedFrom = string | undefined;

export type Tests_Worker_Pipeline_Route_MockEmailContext = {
  id: Tests_Worker_Pipeline_Route_MockEmailContext_Id;
  name: Tests_Worker_Pipeline_Route_MockEmailContext_Name;
  type: Tests_Worker_Pipeline_Route_MockEmailContext_Type;
  interpreter: Tests_Worker_Pipeline_Route_MockEmailContext_Interpreter;
  topic: Tests_Worker_Pipeline_Route_MockEmailContext_Topic;
  error_topic?: Tests_Worker_Pipeline_Route_MockEmailContext_ErrorTopic;
  mode: Tests_Worker_Pipeline_Route_MockEmailContext_Mode;
  show_visitor_info: Tests_Worker_Pipeline_Route_MockEmailContext_ShowVisitorInfo;
  primary_server: Tests_Worker_Pipeline_Route_MockEmailContext_PrimaryServer;
  servers: Tests_Worker_Pipeline_Route_MockEmailContext_Servers;
  allowed_from?: Tests_Worker_Pipeline_Route_MockEmailContext_AllowedFrom;
};

export type Tests_Worker_Pipeline_Route_MockContext = Tests_Worker_Pipeline_Route_MockHttpContext | Tests_Worker_Pipeline_Route_MockEmailContext;

export type Tests_Worker_Pipeline_Route_MockConfig_Settings = Tests_Worker_Pipeline_Route_MockSettings;
export type Tests_Worker_Pipeline_Route_MockConfig_Servers = Tests_Worker_Pipeline_Route_MockServer[];
export type Tests_Worker_Pipeline_Route_MockConfig_Contexts = Tests_Worker_Pipeline_Route_MockContext[];

export type Tests_Worker_Pipeline_Route_MockConfig = {
  settings: Tests_Worker_Pipeline_Route_MockConfig_Settings;
  servers: Tests_Worker_Pipeline_Route_MockConfig_Servers;
  contexts: Tests_Worker_Pipeline_Route_MockConfig_Contexts;
};

export type Tests_Worker_Pipeline_Route_Route_EmailRouting_DoesNotMatchHTTPContextsForEmailRouteType_Result_ContextItem_Name = string;

export type Tests_Worker_Pipeline_Route_Route_EmailRouting_DoesNotMatchHTTPContextsForEmailRouteType_Result_ContextItem = {
  name: Tests_Worker_Pipeline_Route_Route_EmailRouting_DoesNotMatchHTTPContextsForEmailRouteType_Result_ContextItem_Name;
};

export type Tests_Worker_Pipeline_Route_Route_EmailRouting_DoesNotMatchHTTPContextsForEmailRouteType_Result_Context = Tests_Worker_Pipeline_Route_Route_EmailRouting_DoesNotMatchHTTPContextsForEmailRouteType_Result_ContextItem | undefined;

export type Tests_Worker_Pipeline_Route_Route_EmailRouting_DoesNotMatchHTTPContextsForEmailRouteType_Result_ResolvedServersItem_Name = string;

export type Tests_Worker_Pipeline_Route_Route_EmailRouting_DoesNotMatchHTTPContextsForEmailRouteType_Result_ResolvedServersItem = {
  name: Tests_Worker_Pipeline_Route_Route_EmailRouting_DoesNotMatchHTTPContextsForEmailRouteType_Result_ResolvedServersItem_Name;
};

export type Tests_Worker_Pipeline_Route_Route_EmailRouting_DoesNotMatchHTTPContextsForEmailRouteType_Result_ResolvedServers = Tests_Worker_Pipeline_Route_Route_EmailRouting_DoesNotMatchHTTPContextsForEmailRouteType_Result_ResolvedServersItem[] | undefined;

export type Tests_Worker_Pipeline_Route_Route_EmailRouting_DoesNotMatchHTTPContextsForEmailRouteType_Result_PrimaryServerItem_Name = string;

export type Tests_Worker_Pipeline_Route_Route_EmailRouting_DoesNotMatchHTTPContextsForEmailRouteType_Result_PrimaryServerItem = {
  name: Tests_Worker_Pipeline_Route_Route_EmailRouting_DoesNotMatchHTTPContextsForEmailRouteType_Result_PrimaryServerItem_Name;
};

export type Tests_Worker_Pipeline_Route_Route_EmailRouting_DoesNotMatchHTTPContextsForEmailRouteType_Result_PrimaryServer = Tests_Worker_Pipeline_Route_Route_EmailRouting_DoesNotMatchHTTPContextsForEmailRouteType_Result_PrimaryServerItem | undefined;

export type Tests_Worker_Pipeline_Route_Route_EmailRouting_DoesNotMatchHTTPContextsForEmailRouteType_Result_Error = string | undefined;

export type Tests_Worker_Pipeline_Route_Route_EmailRouting_DoesNotMatchHTTPContextsForEmailRouteType_Result = {
  context: Tests_Worker_Pipeline_Route_Route_EmailRouting_DoesNotMatchHTTPContextsForEmailRouteType_Result_Context;
  resolvedServers: Tests_Worker_Pipeline_Route_Route_EmailRouting_DoesNotMatchHTTPContextsForEmailRouteType_Result_ResolvedServers;
  primaryServer: Tests_Worker_Pipeline_Route_Route_EmailRouting_DoesNotMatchHTTPContextsForEmailRouteType_Result_PrimaryServer;
  error: Tests_Worker_Pipeline_Route_Route_EmailRouting_DoesNotMatchHTTPContextsForEmailRouteType_Result_Error;
};

export type Tests_Worker_Pipeline_Route_Route_EmailRouting_IdentifiesThePrimaryServerForEmailContext_Result_ContextItem_Name = string;

export type Tests_Worker_Pipeline_Route_Route_EmailRouting_IdentifiesThePrimaryServerForEmailContext_Result_ContextItem = {
  name: Tests_Worker_Pipeline_Route_Route_EmailRouting_IdentifiesThePrimaryServerForEmailContext_Result_ContextItem_Name;
};

export type Tests_Worker_Pipeline_Route_Route_EmailRouting_IdentifiesThePrimaryServerForEmailContext_Result_Context = Tests_Worker_Pipeline_Route_Route_EmailRouting_IdentifiesThePrimaryServerForEmailContext_Result_ContextItem | undefined;

export type Tests_Worker_Pipeline_Route_Route_EmailRouting_IdentifiesThePrimaryServerForEmailContext_Result_ResolvedServersItem_Name = string;

export type Tests_Worker_Pipeline_Route_Route_EmailRouting_IdentifiesThePrimaryServerForEmailContext_Result_ResolvedServersItem = {
  name: Tests_Worker_Pipeline_Route_Route_EmailRouting_IdentifiesThePrimaryServerForEmailContext_Result_ResolvedServersItem_Name;
};

export type Tests_Worker_Pipeline_Route_Route_EmailRouting_IdentifiesThePrimaryServerForEmailContext_Result_ResolvedServers = Tests_Worker_Pipeline_Route_Route_EmailRouting_IdentifiesThePrimaryServerForEmailContext_Result_ResolvedServersItem[] | undefined;

export type Tests_Worker_Pipeline_Route_Route_EmailRouting_IdentifiesThePrimaryServerForEmailContext_Result_PrimaryServerItem_Name = string;

export type Tests_Worker_Pipeline_Route_Route_EmailRouting_IdentifiesThePrimaryServerForEmailContext_Result_PrimaryServerItem = {
  name: Tests_Worker_Pipeline_Route_Route_EmailRouting_IdentifiesThePrimaryServerForEmailContext_Result_PrimaryServerItem_Name;
};

export type Tests_Worker_Pipeline_Route_Route_EmailRouting_IdentifiesThePrimaryServerForEmailContext_Result_PrimaryServer = Tests_Worker_Pipeline_Route_Route_EmailRouting_IdentifiesThePrimaryServerForEmailContext_Result_PrimaryServerItem | undefined;

export type Tests_Worker_Pipeline_Route_Route_EmailRouting_IdentifiesThePrimaryServerForEmailContext_Result_Error = string | undefined;

export type Tests_Worker_Pipeline_Route_Route_EmailRouting_IdentifiesThePrimaryServerForEmailContext_Result = {
  context: Tests_Worker_Pipeline_Route_Route_EmailRouting_IdentifiesThePrimaryServerForEmailContext_Result_Context;
  resolvedServers: Tests_Worker_Pipeline_Route_Route_EmailRouting_IdentifiesThePrimaryServerForEmailContext_Result_ResolvedServers;
  primaryServer: Tests_Worker_Pipeline_Route_Route_EmailRouting_IdentifiesThePrimaryServerForEmailContext_Result_PrimaryServer;
  error: Tests_Worker_Pipeline_Route_Route_EmailRouting_IdentifiesThePrimaryServerForEmailContext_Result_Error;
};

export type Tests_Worker_Pipeline_Route_Route_EmailRouting_MatchesAContextByIdForEmailType_Result_ContextItem_Name = string;

export type Tests_Worker_Pipeline_Route_Route_EmailRouting_MatchesAContextByIdForEmailType_Result_ContextItem = {
  name: Tests_Worker_Pipeline_Route_Route_EmailRouting_MatchesAContextByIdForEmailType_Result_ContextItem_Name;
};

export type Tests_Worker_Pipeline_Route_Route_EmailRouting_MatchesAContextByIdForEmailType_Result_Context = Tests_Worker_Pipeline_Route_Route_EmailRouting_MatchesAContextByIdForEmailType_Result_ContextItem | undefined;

export type Tests_Worker_Pipeline_Route_Route_EmailRouting_MatchesAContextByIdForEmailType_Result_ResolvedServersItem_Name = string;

export type Tests_Worker_Pipeline_Route_Route_EmailRouting_MatchesAContextByIdForEmailType_Result_ResolvedServersItem = {
  name: Tests_Worker_Pipeline_Route_Route_EmailRouting_MatchesAContextByIdForEmailType_Result_ResolvedServersItem_Name;
};

export type Tests_Worker_Pipeline_Route_Route_EmailRouting_MatchesAContextByIdForEmailType_Result_ResolvedServers = Tests_Worker_Pipeline_Route_Route_EmailRouting_MatchesAContextByIdForEmailType_Result_ResolvedServersItem[] | undefined;

export type Tests_Worker_Pipeline_Route_Route_EmailRouting_MatchesAContextByIdForEmailType_Result_PrimaryServerItem_Name = string;

export type Tests_Worker_Pipeline_Route_Route_EmailRouting_MatchesAContextByIdForEmailType_Result_PrimaryServerItem = {
  name: Tests_Worker_Pipeline_Route_Route_EmailRouting_MatchesAContextByIdForEmailType_Result_PrimaryServerItem_Name;
};

export type Tests_Worker_Pipeline_Route_Route_EmailRouting_MatchesAContextByIdForEmailType_Result_PrimaryServer = Tests_Worker_Pipeline_Route_Route_EmailRouting_MatchesAContextByIdForEmailType_Result_PrimaryServerItem | undefined;

export type Tests_Worker_Pipeline_Route_Route_EmailRouting_MatchesAContextByIdForEmailType_Result_Error = string | undefined;

export type Tests_Worker_Pipeline_Route_Route_EmailRouting_MatchesAContextByIdForEmailType_Result = {
  context: Tests_Worker_Pipeline_Route_Route_EmailRouting_MatchesAContextByIdForEmailType_Result_Context;
  resolvedServers: Tests_Worker_Pipeline_Route_Route_EmailRouting_MatchesAContextByIdForEmailType_Result_ResolvedServers;
  primaryServer: Tests_Worker_Pipeline_Route_Route_EmailRouting_MatchesAContextByIdForEmailType_Result_PrimaryServer;
  error: Tests_Worker_Pipeline_Route_Route_EmailRouting_MatchesAContextByIdForEmailType_Result_Error;
};

export type Tests_Worker_Pipeline_Route_Route_EmailRouting_ResolvesServerConfigsForEmailContext_Result_ContextItem_Name = string;

export type Tests_Worker_Pipeline_Route_Route_EmailRouting_ResolvesServerConfigsForEmailContext_Result_ContextItem = {
  name: Tests_Worker_Pipeline_Route_Route_EmailRouting_ResolvesServerConfigsForEmailContext_Result_ContextItem_Name;
};

export type Tests_Worker_Pipeline_Route_Route_EmailRouting_ResolvesServerConfigsForEmailContext_Result_Context = Tests_Worker_Pipeline_Route_Route_EmailRouting_ResolvesServerConfigsForEmailContext_Result_ContextItem | undefined;

export type Tests_Worker_Pipeline_Route_Route_EmailRouting_ResolvesServerConfigsForEmailContext_Result_ResolvedServersItem_Name = string;

export type Tests_Worker_Pipeline_Route_Route_EmailRouting_ResolvesServerConfigsForEmailContext_Result_ResolvedServersItem = {
  name: Tests_Worker_Pipeline_Route_Route_EmailRouting_ResolvesServerConfigsForEmailContext_Result_ResolvedServersItem_Name;
};

export type Tests_Worker_Pipeline_Route_Route_EmailRouting_ResolvesServerConfigsForEmailContext_Result_ResolvedServers = Tests_Worker_Pipeline_Route_Route_EmailRouting_ResolvesServerConfigsForEmailContext_Result_ResolvedServersItem[] | undefined;

export type Tests_Worker_Pipeline_Route_Route_EmailRouting_ResolvesServerConfigsForEmailContext_Result_PrimaryServerItem_Name = string;

export type Tests_Worker_Pipeline_Route_Route_EmailRouting_ResolvesServerConfigsForEmailContext_Result_PrimaryServerItem = {
  name: Tests_Worker_Pipeline_Route_Route_EmailRouting_ResolvesServerConfigsForEmailContext_Result_PrimaryServerItem_Name;
};

export type Tests_Worker_Pipeline_Route_Route_EmailRouting_ResolvesServerConfigsForEmailContext_Result_PrimaryServer = Tests_Worker_Pipeline_Route_Route_EmailRouting_ResolvesServerConfigsForEmailContext_Result_PrimaryServerItem | undefined;

export type Tests_Worker_Pipeline_Route_Route_EmailRouting_ResolvesServerConfigsForEmailContext_Result_Error = string | undefined;

export type Tests_Worker_Pipeline_Route_Route_EmailRouting_ResolvesServerConfigsForEmailContext_Result = {
  context: Tests_Worker_Pipeline_Route_Route_EmailRouting_ResolvesServerConfigsForEmailContext_Result_Context;
  resolvedServers: Tests_Worker_Pipeline_Route_Route_EmailRouting_ResolvesServerConfigsForEmailContext_Result_ResolvedServers;
  primaryServer: Tests_Worker_Pipeline_Route_Route_EmailRouting_ResolvesServerConfigsForEmailContext_Result_PrimaryServer;
  error: Tests_Worker_Pipeline_Route_Route_EmailRouting_ResolvesServerConfigsForEmailContext_Result_Error;
};

export type Tests_Worker_Pipeline_Route_Route_EmailRouting_ReturnsErrorWhenNoEmailContextMatches_Result_ContextItem_Name = string;

export type Tests_Worker_Pipeline_Route_Route_EmailRouting_ReturnsErrorWhenNoEmailContextMatches_Result_ContextItem = {
  name: Tests_Worker_Pipeline_Route_Route_EmailRouting_ReturnsErrorWhenNoEmailContextMatches_Result_ContextItem_Name;
};

export type Tests_Worker_Pipeline_Route_Route_EmailRouting_ReturnsErrorWhenNoEmailContextMatches_Result_Context = Tests_Worker_Pipeline_Route_Route_EmailRouting_ReturnsErrorWhenNoEmailContextMatches_Result_ContextItem | undefined;

export type Tests_Worker_Pipeline_Route_Route_EmailRouting_ReturnsErrorWhenNoEmailContextMatches_Result_ResolvedServersItem_Name = string;

export type Tests_Worker_Pipeline_Route_Route_EmailRouting_ReturnsErrorWhenNoEmailContextMatches_Result_ResolvedServersItem = {
  name: Tests_Worker_Pipeline_Route_Route_EmailRouting_ReturnsErrorWhenNoEmailContextMatches_Result_ResolvedServersItem_Name;
};

export type Tests_Worker_Pipeline_Route_Route_EmailRouting_ReturnsErrorWhenNoEmailContextMatches_Result_ResolvedServers = Tests_Worker_Pipeline_Route_Route_EmailRouting_ReturnsErrorWhenNoEmailContextMatches_Result_ResolvedServersItem[] | undefined;

export type Tests_Worker_Pipeline_Route_Route_EmailRouting_ReturnsErrorWhenNoEmailContextMatches_Result_PrimaryServerItem_Name = string;

export type Tests_Worker_Pipeline_Route_Route_EmailRouting_ReturnsErrorWhenNoEmailContextMatches_Result_PrimaryServerItem = {
  name: Tests_Worker_Pipeline_Route_Route_EmailRouting_ReturnsErrorWhenNoEmailContextMatches_Result_PrimaryServerItem_Name;
};

export type Tests_Worker_Pipeline_Route_Route_EmailRouting_ReturnsErrorWhenNoEmailContextMatches_Result_PrimaryServer = Tests_Worker_Pipeline_Route_Route_EmailRouting_ReturnsErrorWhenNoEmailContextMatches_Result_PrimaryServerItem | undefined;

export type Tests_Worker_Pipeline_Route_Route_EmailRouting_ReturnsErrorWhenNoEmailContextMatches_Result_Error = string | undefined;

export type Tests_Worker_Pipeline_Route_Route_EmailRouting_ReturnsErrorWhenNoEmailContextMatches_Result = {
  context: Tests_Worker_Pipeline_Route_Route_EmailRouting_ReturnsErrorWhenNoEmailContextMatches_Result_Context;
  resolvedServers: Tests_Worker_Pipeline_Route_Route_EmailRouting_ReturnsErrorWhenNoEmailContextMatches_Result_ResolvedServers;
  primaryServer: Tests_Worker_Pipeline_Route_Route_EmailRouting_ReturnsErrorWhenNoEmailContextMatches_Result_PrimaryServer;
  error: Tests_Worker_Pipeline_Route_Route_EmailRouting_ReturnsErrorWhenNoEmailContextMatches_Result_Error;
};

export type Tests_Worker_Pipeline_Route_Route_HTTPRouting_DoesNotMatchEmailContextsForHTTPRouteType_Result_ContextItem_Name = string;

export type Tests_Worker_Pipeline_Route_Route_HTTPRouting_DoesNotMatchEmailContextsForHTTPRouteType_Result_ContextItem = {
  name: Tests_Worker_Pipeline_Route_Route_HTTPRouting_DoesNotMatchEmailContextsForHTTPRouteType_Result_ContextItem_Name;
};

export type Tests_Worker_Pipeline_Route_Route_HTTPRouting_DoesNotMatchEmailContextsForHTTPRouteType_Result_Context = Tests_Worker_Pipeline_Route_Route_HTTPRouting_DoesNotMatchEmailContextsForHTTPRouteType_Result_ContextItem | undefined;

export type Tests_Worker_Pipeline_Route_Route_HTTPRouting_DoesNotMatchEmailContextsForHTTPRouteType_Result_ResolvedServersItem_Name = string;

export type Tests_Worker_Pipeline_Route_Route_HTTPRouting_DoesNotMatchEmailContextsForHTTPRouteType_Result_ResolvedServersItem = {
  name: Tests_Worker_Pipeline_Route_Route_HTTPRouting_DoesNotMatchEmailContextsForHTTPRouteType_Result_ResolvedServersItem_Name;
};

export type Tests_Worker_Pipeline_Route_Route_HTTPRouting_DoesNotMatchEmailContextsForHTTPRouteType_Result_ResolvedServers = Tests_Worker_Pipeline_Route_Route_HTTPRouting_DoesNotMatchEmailContextsForHTTPRouteType_Result_ResolvedServersItem[] | undefined;

export type Tests_Worker_Pipeline_Route_Route_HTTPRouting_DoesNotMatchEmailContextsForHTTPRouteType_Result_PrimaryServerItem_Name = string;

export type Tests_Worker_Pipeline_Route_Route_HTTPRouting_DoesNotMatchEmailContextsForHTTPRouteType_Result_PrimaryServerItem = {
  name: Tests_Worker_Pipeline_Route_Route_HTTPRouting_DoesNotMatchEmailContextsForHTTPRouteType_Result_PrimaryServerItem_Name;
};

export type Tests_Worker_Pipeline_Route_Route_HTTPRouting_DoesNotMatchEmailContextsForHTTPRouteType_Result_PrimaryServer = Tests_Worker_Pipeline_Route_Route_HTTPRouting_DoesNotMatchEmailContextsForHTTPRouteType_Result_PrimaryServerItem | undefined;

export type Tests_Worker_Pipeline_Route_Route_HTTPRouting_DoesNotMatchEmailContextsForHTTPRouteType_Result_Error = string | undefined;

export type Tests_Worker_Pipeline_Route_Route_HTTPRouting_DoesNotMatchEmailContextsForHTTPRouteType_Result = {
  context: Tests_Worker_Pipeline_Route_Route_HTTPRouting_DoesNotMatchEmailContextsForHTTPRouteType_Result_Context;
  resolvedServers: Tests_Worker_Pipeline_Route_Route_HTTPRouting_DoesNotMatchEmailContextsForHTTPRouteType_Result_ResolvedServers;
  primaryServer: Tests_Worker_Pipeline_Route_Route_HTTPRouting_DoesNotMatchEmailContextsForHTTPRouteType_Result_PrimaryServer;
  error: Tests_Worker_Pipeline_Route_Route_HTTPRouting_DoesNotMatchEmailContextsForHTTPRouteType_Result_Error;
};

export type Tests_Worker_Pipeline_Route_Route_HTTPRouting_IdentifiesThePrimaryServer_Result_ContextItem_Name = string;

export type Tests_Worker_Pipeline_Route_Route_HTTPRouting_IdentifiesThePrimaryServer_Result_ContextItem = {
  name: Tests_Worker_Pipeline_Route_Route_HTTPRouting_IdentifiesThePrimaryServer_Result_ContextItem_Name;
};

export type Tests_Worker_Pipeline_Route_Route_HTTPRouting_IdentifiesThePrimaryServer_Result_Context = Tests_Worker_Pipeline_Route_Route_HTTPRouting_IdentifiesThePrimaryServer_Result_ContextItem | undefined;

export type Tests_Worker_Pipeline_Route_Route_HTTPRouting_IdentifiesThePrimaryServer_Result_ResolvedServersItem_Name = string;

export type Tests_Worker_Pipeline_Route_Route_HTTPRouting_IdentifiesThePrimaryServer_Result_ResolvedServersItem = {
  name: Tests_Worker_Pipeline_Route_Route_HTTPRouting_IdentifiesThePrimaryServer_Result_ResolvedServersItem_Name;
};

export type Tests_Worker_Pipeline_Route_Route_HTTPRouting_IdentifiesThePrimaryServer_Result_ResolvedServers = Tests_Worker_Pipeline_Route_Route_HTTPRouting_IdentifiesThePrimaryServer_Result_ResolvedServersItem[] | undefined;

export type Tests_Worker_Pipeline_Route_Route_HTTPRouting_IdentifiesThePrimaryServer_Result_PrimaryServerItem_Name = string;

export type Tests_Worker_Pipeline_Route_Route_HTTPRouting_IdentifiesThePrimaryServer_Result_PrimaryServerItem = {
  name: Tests_Worker_Pipeline_Route_Route_HTTPRouting_IdentifiesThePrimaryServer_Result_PrimaryServerItem_Name;
};

export type Tests_Worker_Pipeline_Route_Route_HTTPRouting_IdentifiesThePrimaryServer_Result_PrimaryServer = Tests_Worker_Pipeline_Route_Route_HTTPRouting_IdentifiesThePrimaryServer_Result_PrimaryServerItem | undefined;

export type Tests_Worker_Pipeline_Route_Route_HTTPRouting_IdentifiesThePrimaryServer_Result_Error = string | undefined;

export type Tests_Worker_Pipeline_Route_Route_HTTPRouting_IdentifiesThePrimaryServer_Result = {
  context: Tests_Worker_Pipeline_Route_Route_HTTPRouting_IdentifiesThePrimaryServer_Result_Context;
  resolvedServers: Tests_Worker_Pipeline_Route_Route_HTTPRouting_IdentifiesThePrimaryServer_Result_ResolvedServers;
  primaryServer: Tests_Worker_Pipeline_Route_Route_HTTPRouting_IdentifiesThePrimaryServer_Result_PrimaryServer;
  error: Tests_Worker_Pipeline_Route_Route_HTTPRouting_IdentifiesThePrimaryServer_Result_Error;
};

export type Tests_Worker_Pipeline_Route_Route_HTTPRouting_MatchesAContextByIdForHTTPType_Result_ContextItem_Name = string;

export type Tests_Worker_Pipeline_Route_Route_HTTPRouting_MatchesAContextByIdForHTTPType_Result_ContextItem = {
  name: Tests_Worker_Pipeline_Route_Route_HTTPRouting_MatchesAContextByIdForHTTPType_Result_ContextItem_Name;
};

export type Tests_Worker_Pipeline_Route_Route_HTTPRouting_MatchesAContextByIdForHTTPType_Result_Context = Tests_Worker_Pipeline_Route_Route_HTTPRouting_MatchesAContextByIdForHTTPType_Result_ContextItem | undefined;

export type Tests_Worker_Pipeline_Route_Route_HTTPRouting_MatchesAContextByIdForHTTPType_Result_ResolvedServersItem_Name = string;

export type Tests_Worker_Pipeline_Route_Route_HTTPRouting_MatchesAContextByIdForHTTPType_Result_ResolvedServersItem = {
  name: Tests_Worker_Pipeline_Route_Route_HTTPRouting_MatchesAContextByIdForHTTPType_Result_ResolvedServersItem_Name;
};

export type Tests_Worker_Pipeline_Route_Route_HTTPRouting_MatchesAContextByIdForHTTPType_Result_ResolvedServers = Tests_Worker_Pipeline_Route_Route_HTTPRouting_MatchesAContextByIdForHTTPType_Result_ResolvedServersItem[] | undefined;

export type Tests_Worker_Pipeline_Route_Route_HTTPRouting_MatchesAContextByIdForHTTPType_Result_PrimaryServerItem_Name = string;

export type Tests_Worker_Pipeline_Route_Route_HTTPRouting_MatchesAContextByIdForHTTPType_Result_PrimaryServerItem = {
  name: Tests_Worker_Pipeline_Route_Route_HTTPRouting_MatchesAContextByIdForHTTPType_Result_PrimaryServerItem_Name;
};

export type Tests_Worker_Pipeline_Route_Route_HTTPRouting_MatchesAContextByIdForHTTPType_Result_PrimaryServer = Tests_Worker_Pipeline_Route_Route_HTTPRouting_MatchesAContextByIdForHTTPType_Result_PrimaryServerItem | undefined;

export type Tests_Worker_Pipeline_Route_Route_HTTPRouting_MatchesAContextByIdForHTTPType_Result_Error = string | undefined;

export type Tests_Worker_Pipeline_Route_Route_HTTPRouting_MatchesAContextByIdForHTTPType_Result = {
  context: Tests_Worker_Pipeline_Route_Route_HTTPRouting_MatchesAContextByIdForHTTPType_Result_Context;
  resolvedServers: Tests_Worker_Pipeline_Route_Route_HTTPRouting_MatchesAContextByIdForHTTPType_Result_ResolvedServers;
  primaryServer: Tests_Worker_Pipeline_Route_Route_HTTPRouting_MatchesAContextByIdForHTTPType_Result_PrimaryServer;
  error: Tests_Worker_Pipeline_Route_Route_HTTPRouting_MatchesAContextByIdForHTTPType_Result_Error;
};

export type Tests_Worker_Pipeline_Route_Route_HTTPRouting_ResolvesServerConfigsFromContextServerNames_Result_ContextItem_Name = string;

export type Tests_Worker_Pipeline_Route_Route_HTTPRouting_ResolvesServerConfigsFromContextServerNames_Result_ContextItem = {
  name: Tests_Worker_Pipeline_Route_Route_HTTPRouting_ResolvesServerConfigsFromContextServerNames_Result_ContextItem_Name;
};

export type Tests_Worker_Pipeline_Route_Route_HTTPRouting_ResolvesServerConfigsFromContextServerNames_Result_Context = Tests_Worker_Pipeline_Route_Route_HTTPRouting_ResolvesServerConfigsFromContextServerNames_Result_ContextItem | undefined;

export type Tests_Worker_Pipeline_Route_Route_HTTPRouting_ResolvesServerConfigsFromContextServerNames_Result_ResolvedServersItem_Name = string;

export type Tests_Worker_Pipeline_Route_Route_HTTPRouting_ResolvesServerConfigsFromContextServerNames_Result_ResolvedServersItem = {
  name: Tests_Worker_Pipeline_Route_Route_HTTPRouting_ResolvesServerConfigsFromContextServerNames_Result_ResolvedServersItem_Name;
};

export type Tests_Worker_Pipeline_Route_Route_HTTPRouting_ResolvesServerConfigsFromContextServerNames_Result_ResolvedServers = Tests_Worker_Pipeline_Route_Route_HTTPRouting_ResolvesServerConfigsFromContextServerNames_Result_ResolvedServersItem[] | undefined;

export type Tests_Worker_Pipeline_Route_Route_HTTPRouting_ResolvesServerConfigsFromContextServerNames_Result_PrimaryServerItem_Name = string;

export type Tests_Worker_Pipeline_Route_Route_HTTPRouting_ResolvesServerConfigsFromContextServerNames_Result_PrimaryServerItem = {
  name: Tests_Worker_Pipeline_Route_Route_HTTPRouting_ResolvesServerConfigsFromContextServerNames_Result_PrimaryServerItem_Name;
};

export type Tests_Worker_Pipeline_Route_Route_HTTPRouting_ResolvesServerConfigsFromContextServerNames_Result_PrimaryServer = Tests_Worker_Pipeline_Route_Route_HTTPRouting_ResolvesServerConfigsFromContextServerNames_Result_PrimaryServerItem | undefined;

export type Tests_Worker_Pipeline_Route_Route_HTTPRouting_ResolvesServerConfigsFromContextServerNames_Result_Error = string | undefined;

export type Tests_Worker_Pipeline_Route_Route_HTTPRouting_ResolvesServerConfigsFromContextServerNames_Result = {
  context: Tests_Worker_Pipeline_Route_Route_HTTPRouting_ResolvesServerConfigsFromContextServerNames_Result_Context;
  resolvedServers: Tests_Worker_Pipeline_Route_Route_HTTPRouting_ResolvesServerConfigsFromContextServerNames_Result_ResolvedServers;
  primaryServer: Tests_Worker_Pipeline_Route_Route_HTTPRouting_ResolvesServerConfigsFromContextServerNames_Result_PrimaryServer;
  error: Tests_Worker_Pipeline_Route_Route_HTTPRouting_ResolvesServerConfigsFromContextServerNames_Result_Error;
};

export type Tests_Worker_Pipeline_Route_Route_HTTPRouting_ReturnsErrorWhenNoContextMatches_Result_ContextItem_Name = string;

export type Tests_Worker_Pipeline_Route_Route_HTTPRouting_ReturnsErrorWhenNoContextMatches_Result_ContextItem = {
  name: Tests_Worker_Pipeline_Route_Route_HTTPRouting_ReturnsErrorWhenNoContextMatches_Result_ContextItem_Name;
};

export type Tests_Worker_Pipeline_Route_Route_HTTPRouting_ReturnsErrorWhenNoContextMatches_Result_Context = Tests_Worker_Pipeline_Route_Route_HTTPRouting_ReturnsErrorWhenNoContextMatches_Result_ContextItem | undefined;

export type Tests_Worker_Pipeline_Route_Route_HTTPRouting_ReturnsErrorWhenNoContextMatches_Result_ResolvedServersItem_Name = string;

export type Tests_Worker_Pipeline_Route_Route_HTTPRouting_ReturnsErrorWhenNoContextMatches_Result_ResolvedServersItem = {
  name: Tests_Worker_Pipeline_Route_Route_HTTPRouting_ReturnsErrorWhenNoContextMatches_Result_ResolvedServersItem_Name;
};

export type Tests_Worker_Pipeline_Route_Route_HTTPRouting_ReturnsErrorWhenNoContextMatches_Result_ResolvedServers = Tests_Worker_Pipeline_Route_Route_HTTPRouting_ReturnsErrorWhenNoContextMatches_Result_ResolvedServersItem[] | undefined;

export type Tests_Worker_Pipeline_Route_Route_HTTPRouting_ReturnsErrorWhenNoContextMatches_Result_PrimaryServerItem_Name = string;

export type Tests_Worker_Pipeline_Route_Route_HTTPRouting_ReturnsErrorWhenNoContextMatches_Result_PrimaryServerItem = {
  name: Tests_Worker_Pipeline_Route_Route_HTTPRouting_ReturnsErrorWhenNoContextMatches_Result_PrimaryServerItem_Name;
};

export type Tests_Worker_Pipeline_Route_Route_HTTPRouting_ReturnsErrorWhenNoContextMatches_Result_PrimaryServer = Tests_Worker_Pipeline_Route_Route_HTTPRouting_ReturnsErrorWhenNoContextMatches_Result_PrimaryServerItem | undefined;

export type Tests_Worker_Pipeline_Route_Route_HTTPRouting_ReturnsErrorWhenNoContextMatches_Result_Error = string | undefined;

export type Tests_Worker_Pipeline_Route_Route_HTTPRouting_ReturnsErrorWhenNoContextMatches_Result = {
  context: Tests_Worker_Pipeline_Route_Route_HTTPRouting_ReturnsErrorWhenNoContextMatches_Result_Context;
  resolvedServers: Tests_Worker_Pipeline_Route_Route_HTTPRouting_ReturnsErrorWhenNoContextMatches_Result_ResolvedServers;
  primaryServer: Tests_Worker_Pipeline_Route_Route_HTTPRouting_ReturnsErrorWhenNoContextMatches_Result_PrimaryServer;
  error: Tests_Worker_Pipeline_Route_Route_HTTPRouting_ReturnsErrorWhenNoContextMatches_Result_Error;
};
