name: Bug Report
description: Found an unexpected issue or problem? Report it here.
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: We truly appreciate you taking the time to share this bug report with us.
  - type: markdown
    attributes:
      value: Please __fill out the form with as much detail as possible__ so the contributors can easily recreate the issue and work swiftly to assist you in resolving it. Thank you for your cooperation!
  - type: markdown
    attributes:
      value: ---
  - type: checkboxes
    id: pre-check
    attributes:
      label: Pre-check confirmation
      description: Before proceeding further, please confirm the following by checking each box. This confirmation is crucial for contributors to effectively identify and address the issue. __All boxes MUST be checked; failure to comply will result in the immediate closure of this issue.__
      options:
        - label: I have included a title detailing an issue I am having.
          required: true
        - label: I have done my research, and this is __NOT__ a duplicate bug report.
          required: true
        - label: I am __NOT__ requesting a new feature.
          required: true
        - label: I am using the latest version of the plugin.
          required: true
  - type: input
    id: email
    attributes:
      label: Your email address
      description: Help the contributors easily get in touch with you if they need more information. __If possible, please consider using an alias you have access to as this information will be seen by the public.__
      placeholder: e.g. user@example.com
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: Can you tell us exactly what happened?
      description: Provide a comprehensive description of __the steps or circumstances__ that led to the occurrence of this issue.
      placeholder: e.g. When I was doing ..., I expected ... to happen, but I got ... instead.
    validations:
      required: true
  - type: input
    id: plugin-version
    attributes:
      label: Plugin version
      description: What version of the plugin are you using? If you are using the Homebridge Config UI, you may find this information in the "Plugins" tab, or inside the logs similar to `[1/1/2024, 12:00:00 AM] [ADT Pulse] running on` (shown when Homebridge starts).
      placeholder: e.g. 3.0.0
    validations:
      required: true
  - type: input
    id: homebridge-version
    attributes:
      label: Homebridge version
      description: What version of Homebridge are you using? You may find this information in the "System Information" widget when using the Homebridge Config UI or by running the `homebridge -V` command.
      placeholder: e.g. 1.7.0
    validations:
      required: true
  - type: input
    id: node-version
    attributes:
      label: Node.js® version
      description: What version of Node.js® are you using? __Please be aware using a version with the latest features may not be supported.__ It is recommended that you use versions that are "Recommended for Most Users" or under "Long Term Support (LTS)" as listed in the [Node.js® homepage](https://nodejs.org).
      placeholder: e.g. 20.10.0
    validations:
      required: true
  - type: textarea
    id: test-api-logs
    attributes:
      label: Log output of the `test-api` command
      description: From the Homebridge plugin path, most likely will be `/var/lib/homebridge/node_modules`, run this command `cd homebridge-adt-pulse && npm run test-api` and paste in the results below. __Do not include logs from other plugins or commands.__ This block will be automatically formatted into code, so __no need for backticks__.
      render: shell
    validations:
      required: true
  - type: textarea
    id: more-logs
    attributes:
      label: More logs relevant to this issue
      description: Please copy and paste all logs related to this bug. __Do not include logs from other plugins or commands.__ This block will be automatically formatted into code, so __no need for backticks__.
      render: shell
    validations:
      required: true
  - type: checkboxes
    id: legal
    attributes:
      label: Legal Agreements
      description: By submitting a new bug report, you have read, understood, and agree to the [Terms of Use](https://www.cbnventures.io/terms/) and [Privacy Policy](https://www.cbnventures.io/privacy/). If you have questions about these policies, feel free to [get in touch](https://www.cbnventures.io/get-in-touch/) with us.
      options:
        - label: I agree to the Terms of Use and Privacy Policy
          required: true
