name: Feature Request
description: Have a new feature in mind? Share your request with us.
title: "[Feature Request]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: Thank you for contributing to the improvement of this project by submitting a feature request!
  - type: markdown
    attributes:
      value: Please __fill out the form below__ to help the contributors understand your feature request better. Your input is valuable in shaping the future of this project.
  - type: markdown
    attributes:
      value: ---
  - type: checkboxes
    id: pre-check
    attributes:
      label: Pre-check confirmation
      description: Before proceeding further, please confirm the following by checking each box. This confirmation is crucial for the consideration of your feature request. __All boxes MUST be checked; failure to comply may result in your request being closed.__
      options:
        - label: I have provided a descriptive title for my feature request.
          required: true
        - label: I have confirmed that this feature is __NOT__ already present or planned.
          required: true
  - type: input
    id: email
    attributes:
      label: Your email address
      description: Help us reach out to you if the contributors need more information or clarification on your feature request. __If possible, please use an alias you have access to as this information will be seen by the public.__
      placeholder: e.g. user@example.com
    validations:
      required: true
  - type: textarea
    id: feature-description
    attributes:
      label: Describe the new feature you are requesting
      description: Provide a detailed description of the feature you would like to see implemented. Include any relevant information or use cases that might help the contributors understand the need for this feature.
      placeholder: e.g. I would like a new feature that allows...
    validations:
      required: true
  - type: checkboxes
    id: legal
    attributes:
      label: Legal Agreements
      description: By submitting a new feature request, you confirm that you have read, understood, and agree to the [Terms of Use](https://www.cbnventures.io/terms/) and [Privacy Policy](https://www.cbnventures.io/privacy/). If you have questions about these policies, feel free to [get in touch](https://www.cbnventures.io/get-in-touch/) with us.
      options:
        - label: I agree to the Terms of Use and Privacy Policy
          required: true
